#ifndef _MEDIA__DRIVER_KERNELS_G7_H
#define _MEDIA__DRIVER_KERNELS_G7_H
#include "media_drv_defines.h"

#define MEDIA_VP8_MBENC_I_SZ_G7 0x62c0
extern const UINT MEDIA_VP8_MBENC_I_G7[MEDIA_VP8_MBENC_I_SZ_G7];

#define MEDIA_VP8_MBENC_ICHROMA_SZ_G7 0xe300	//0xe310
extern const UINT MEDIA_VP8_MBENC_ICHROMA_G7[MEDIA_VP8_MBENC_ICHROMA_SZ_G7];

#define MEDIA_VP8_MBENC_FRM_P_SZ_G7 0xb1c0
extern const UINT MEDIA_VP8_MBENC_FRM_P_G7[MEDIA_VP8_MBENC_FRM_P_SZ_G7];

#define MEDIA_VP8_PAK_PHASE1_SZ_G7 0x7940
extern const UINT MEDIA_VP8_PAK_PHASE1_G7[MEDIA_VP8_PAK_PHASE1_SZ_G7];

#define MEDIA_VP8_PAK_PHASE2_SZ_G7 0x9af0
extern const UINT MEDIA_VP8_PAK_PHASE2_G7[MEDIA_VP8_PAK_PHASE2_SZ_G7];
#endif
